document.getElementById("gerar").addEventListener("click", function () {
    const nomes = {
        personagens: ["Gandalf", "Frodo", "Aragorn", "Legolas", "Gollum", "Dumbledore", "Harry", "Hermione", "Ron", "Voldemort", "Batman", "Superman", "Coringa", "Aquaman", "Flash", "Lanterna Verde", "Darth Vader", "Yoda", "Obi-Wan", "Luke", "Leia", "Anakin", "Chewbacca", "R2-D2", "C-3PO", "Sonic", "Mario", "Luigi", "Bowser", "Donkey Kong", "Link", "Zelda", "Kratos", "Nathan Drake", "Lara Croft", "Geralt", "Ezio", "Altair", "Connor", "Master Chief", "Samus", "Pikachu", "Charizard", "Mewtwo", "Scorpion", "Sub-Zero", "Raiden", "Ryu", "Ken", "Chun-Li"],
        cidades: ["Tóquio", "Paris", "Nova York", "Londres", "Rio de Janeiro", "São Paulo", "Berlim", "Moscou", "Pequim", "Xangai", "Seul", "Amsterdã", "Roma", "Milão", "Barcelona", "Lisboa", "Buenos Aires", "Bogotá", "Lima", "Santiago", "Dubai", "Los Angeles", "Chicago", "San Francisco", "Toronto", "Vancouver", "Sydney", "Melbourne", "Bangkok", "Istambul", "Atenas", "Praga", "Varsóvia", "Viena", "Bruxelas", "Genebra", "Zurique", "Munique", "Frankfurt", "Estocolmo", "Copenhague", "Helsinque", "Oslo", "Dublin", "Edimburgo", "Kiev", "Budapeste", "Manila", "Jacarta", "Casablanca", "Cairo", "Marrakech"],
        animais: ["Leão", "Tigre", "Lobo", "Águia", "Raposa", "Elefante", "Girafa", "Rinoceronte", "Hipopótamo", "Urso", "Panda", "Cervo", "Anta", "Bicho-preguiça", "Onça", "Jacaré", "Crocodilo", "Camaleão", "Iguana", "Tatu", "Arraia", "Tubarão", "Golfinho", "Orca", "Peixe-palhaço", "Estrela-do-mar", "Falcão", "Coruja", "Gavião", "Papagaio", "Arara", "Tucano", "Galo", "Pato", "Cisne", "Cavalo", "Javali", "Tamanduá", "Gato", "Cachorro", "Coelho", "Rato", "Tartaruga", "Porco", "Ovelha", "Vaca", "Lêmure", "Guaxinim", "Suricato", "Canguru"],
        homem: ["Matheus", "Lucas", "Henan", "Gabriel", "João", "Felipe", "Rafael", "Vinícius", "Gustavo", "Leonardo", "Bruno", "André", "Thiago", "Rodrigo", "Daniel", "Eduardo", "Caio", "Ricardo", "Diego", "Marcelo", "Alexandre", "Fábio", "Fernando", "Victor", "Igor", "Nicolas", "Murilo", "Samuel", "Antônio", "Jorge", "Miguel", "Davi", "Enzo", "Pedro", "Carlos", "Roberto", "William", "César", "Emerson", "Sérgio", "Adriano", "Alan", "Everton", "Márcio", "Osvaldo", "Cristian", "Ivan", "Wallace", "Jonathan", "Eliandro", "Renato"],
        mulher: ["Ana", "Beatriz", "Camila", "Daniela", "Eduarda", "Fernanda", "Gabriela", "Helena", "Isabela", "Júlia", "Karina", "Larissa", "Mariana", "Natália", "Olívia", "Patrícia", "Queila", "Raquel", "Sabrina", "Tatiane", "Úrsula", "Vanessa", "Wendy", "Ximena", "Yasmin", "Zuleica", "Alice", "Bianca", "Carolina", "Débora", "Elisa", "Flávia", "Giovanna", "Heloísa", "Ivone", "Janaina", "Kamilly", "Kelly", "Luana", "Melissa", "Nayara", "Ornella", "Priscila", "Renata", "Sílvia", "Tainá", "Ulrica", "Verônica", "Wilma", "Xandra", "Yara", "Zilda"]
    };

    let categoria = document.getElementById("categoria").value;
    let nomeAleatorio = nomes[categoria][Math.floor(Math.random() * nomes[categoria].length)];

    document.getElementById("resultado").textContent = ` ${nomeAleatorio}`;
});
